services:
  spot2yoto:
    image: ghcr.io/jonathanlinford/spot2yoto:latest
    volumes:
      - ${HOME}/.config/spot2yoto:/root/.config/spot2yoto
      - spot2yoto-state:/root/.local/share/spot2yoto
      - spot2yoto-cache:/root/.cache/spot2yoto
    stdin_open: true
    tty: true

volumes:
  spot2yoto-state:
  spot2yoto-cache:
